mqtt:
  broker: "127.0.0.1"  # Changed to localhost
  port: 1883
  username: ""         # Empty for local test
  password: ""         # Empty for local test
  topic_prefix: "devices"

camera:
  index: 0
  width: 640
  height: 480
  rotation: 0

system:
  direction: "IN"
  debounce_seconds: 10 # Lower this for easier testing
  similarity_threshold: 0.45
  confidence_threshold: 0.5