mqtt:
  broker: "127.0.0.1"  # Changed to localhost
  port: 1883
  username: ""         # Empty for local test
  password: ""         # Empty for local test
  topic_prefix: "devices"

camera:
  index: 0
  width: 640
  height: 480
  rotation: 0

system:
  direction: "IN"
  debounce_seconds: 10
  similarity_threshold: 0.45
  confidence_threshold: 0.5
  # ADD THIS: Default zone (Top-Left, Top-Right, Bot-Right, Bot-Left)
  # If empty [], it scans the whole screen.
  zone: [[0,0], [640,0], [640,480], [0,480]]